### ISSUE TITLE
Setting global variable in before suite actions

### ISSUE THREAD

**Issue by nimskhan** [citrusframework/citrus#306]
Currently, `runner.getVariable()` isn't available in Citrus before suite which extends `TestRunnerBeforeSuiteSupport`. 
What I am dong is:

```
runner.echo("My Value : ${extractedValue}");
final String myValue = runner.variable("tmp", "${extractedValue}");
variables.getVariables().put("Value", myValue);
```

This seems like a hack, could you please suggest a better way of doing it?

**Comment by christophd** [comment]
Your sample code is incomplete in a form that I can not see what you are trying to do. `runner.getVariable()` is not even part of the Citrus API. Please rephrase the question and give a proper code sample.

**Comment by nimskhan** [comment]
Sure.

Actually, I have an authentication URL which we use to fetch oAuth access token. And then on service URL we execute our citrus cases. Here is the flow:

1. In `BeforeSuite` which extends `TestRunnerBeforeSuiteSupport` a SEND request is made to authentication service followed by a GET request to get the access token.
2. The fetched access token is then set to global variables, in order to make it available for rest of the test cases.

For the case stated above I have `BeforeSuite` and `GlobalVariables` defined in CitrusConfig.java as follows:

```
    @Bean
    BeforeSuite beforeSuite() {
        return new BeforeSuite();
    }

    @Bean
    public GlobalVariables globalVariables() {
        return new GlobalVariables();
    }

```

Then I have my before suite class, which looks like this:

```
public class BeforeSuite extends TestRunnerBeforeSuiteSupport {

    @Autowired
    private HttpClient authenticationServiceClient;

    @Autowired
    private GlobalVariables variables;

    @Override
    public void beforeSuite(final TestRunner runner) {
        runner.echo("This action should be executed before suite");
        runner.variable("accessTokenValue", "");

        runner.send(builder -> builder.endpoint(authenticationServiceClient) //
                .message(new HttpMessage(  "client_id=app&client_secret=appclientsecret&grant_type=password&username=myuser&password=pass&response_type=token") //
                .path("/my/app/token/") //
                .method(HttpMethod.POST) //
                .contentType(MediaType.APPLICATION_FORM_URLENCODED_VALUE) //
                .accept(MediaType.APPLICATION_JSON_VALUE)));

        runner.receive(builder -> builder.endpoint(authenticationServiceClient) //
                .message(new HttpMessage() //
                .status(HttpStatus.OK)) //
                .messageType(MessageType.JSON) //
                .extractFromPayload("$.access_token", "${accessTokenValue}"));

        final String token = runner.variable("tmp", "${accessTokenValue}");
        variables.getVariables().put("token", token);
    }
```

I am have used the extracted "access token" in my test case like this:

```
public class AddCategoryIT extends JUnit4CitrusTestRunner {
    @Test
    @CitrusTest
    public void shouldAddResourceStatus(@CitrusResource TestContext context) throws Exception {
        author("Nimra Inam");
        description("some description");
        echo("My access token: ${token}");
    }
}
```

**Comment by christophd** [comment]
Ok, now I see what you are trying to do. 

It is not possible to add/set global variables via test action. Also the runner and test context that you access in the before suite is not the same instance that is used later in your test case. Therefore variables are not visible. This is a design concept that should avoid tests to be dependent on each other which is bad by nature. The autowired global variables will also not help because of this. 

I see the relevance of your code getting the access token once at the very beginning. I would suggest to use a test behavior for that that is applied to the before test lifecycle. The before test lifecycle has access to the test context of the actual test meaning that setting new variables in before test are also visible in test itself.

This could be a better solution for you.

**Comment by nimskhan** [comment]
Thanks for elaborating the solution. I will try it hopefully this will resolve the issue we faced.

**Comment by nimskhan** [comment]
@christophd  I tried the solution suggested above, but the required variable isn't available in my test-case. I have BeforeSuite defined in CitrusConfig.java as follows:

  ```
  @Bean
    BeforeSuite beforeSuite() {
        return new BeforeSuite();
    }
```

Then I have behavior as follows:
 ```
public class AuthenticationBehavior extends AbstractTestBehavior {

    private final HttpClient authenticationServiceClient;

    public AuthenticationBehavior(final HttpClient authenticationServiceClient) {
        this.authenticationServiceClient = authenticationServiceClient;
    }

    public void apply() {

        variable("accessTokenValue", "");

        send(builder -> builder.endpoint(authenticationServiceClient) //
                .message(new HttpMessage(
                        "client_id=app&client_secret=appclientsecret&grant_type=password&username=username&password=password&response_type=token") //
                                .path("/uaa/oauth/token/") //
                                .method(HttpMethod.POST) //
                                .contentType(MediaType.APPLICATION_FORM_URLENCODED_VALUE) //
                                .accept(MediaType.APPLICATION_JSON_VALUE)));

        receive(builder -> builder.endpoint(authenticationServiceClient) //
                .message(new HttpMessage() //
                        .status(HttpStatus.OK)) //
                .messageType(MessageType.JSON) //
                .extractFromPayload("$.access_token", "${accessTokenValue}"));

    }
}
```

Here is BeforeSuite which applies above behavior:
```
public class BeforeSuite extends TestRunnerBeforeSuiteSupport  {

    @Autowired
    private HttpClient authenticationServiceClient;

    @Override
    public void beforeSuite(final TestRunner runner) {
        runner.echo("This action should be executed before suite");

        runner.applyBehavior(new AuthenticationBehavior(authenticationServiceClient));
        runner.echo("Access Token: ${accessTokenValue}");
    }
}
```

The accessToken variable should be available in my test case, but it gives "unknown variable" exception.

```
public class AddCategoryIT extends JUnit4CitrusTestRunner {
    @Test
    @CitrusTest
    public void shouldAddResourceStatus(@CitrusResource TestContext context) throws Exception {
        author("Nimra Inam");
        description("some description");
        echo("My access token: ${token}");
    }
}

````
 
Got following exception:
```
ctiveStatus <com.etilize.burraq.category> Nested exception is: 

com.consol.citrus.exceptions.CitrusRuntimeException: Unknown variable 'accessTokenValue'
	at com.consol.citrus.context.TestContext.getVariableObject(TestContext.java:158)
	at com.consol.citrus.context.TestContext.getVariable(TestContext.java:133)
	at com.consol.citrus.context.TestContext.getVariable(TestContext.java:122)
	at com.consol.citrus.variable.VariableUtils.replaceVariablesInString(VariableUtils.java:175)
	at com.consol.citrus.context.TestContext.replaceDynamicContentInString(TestContext.java:326)
	at com.consol.citrus.context.TestContext.replaceDynamicContentInString(TestContext.java:311)
	at com.consol.citrus.actions.EchoAction.doExecute(EchoAction.java:51)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.TestCase.executeAction(TestCase.java:229)
	at com.consol.citrus.dsl.runner.DefaultTestRunner.run(DefaultTestRunner.java:198)
	at com.consol.citrus.dsl.runner.DefaultTestRunner.echo(DefaultTestRunner.java:237)
	at com.consol.citrus.dsl.junit.JUnit4CitrusTestRunner.echo(JUnit4CitrusTestRunner.java:156)
	at com.etilize.burraq.category.AddCategoryIT.shouldAddCategoryWithActiveStatus(AddCategoryIT.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
	at com.consol.citrus.dsl.junit.JUnit4CitrusTest.invokeTestMethod(JUnit4CitrusTest.java:96)
	at com.consol.citrus.dsl.junit.JUnit4CitrusTest.run(JUnit4CitrusTest.java:71)
	at com.consol.citrus.junit.CitrusJUnit4Runner$InvokeRunMethod.evaluate(CitrusJUnit4Runner.java:212)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

Please suggest.

**Comment by nimskhan** [comment]
@christophd Could you please suggest?

**Comment by christophd** [comment]
You are still using before test suite which is not able to create variables that are visible in the test cases. You should be using before test support instead.

**Comment by nimskhan** [comment]
@christophd The reason to avoid Before Test Support and using Before Test Suite is to have access token extracted only once, in the beginning of the test suite. Using before test support will generated access token before each test case. It's like logging in for each operation.

Whereas, used Before Test Support, it's giving the same exception.
 

```
    @Bean
    BeforeTest beforeTest() {
        return new BeforeTest();
    }
```

Then I have behavior as follows:
 ```
public class AuthenticationBehavior extends AbstractTestBehavior {

    private final HttpClient authenticationServiceClient;

    public AuthenticationBehavior(final HttpClient authenticationServiceClient) {
        this.authenticationServiceClient = authenticationServiceClient;
    }

    public void apply() {

        variable("accessTokenValue", "");

        send(builder -> builder.endpoint(authenticationServiceClient) //
                .message(new HttpMessage(
                        "client_id=app&client_secret=appclientsecret&grant_type=password&username=username&password=password&response_type=token") //
                                .path("/uaa/oauth/token/") //
                                .method(HttpMethod.POST) //
                                .contentType(MediaType.APPLICATION_FORM_URLENCODED_VALUE) //
                                .accept(MediaType.APPLICATION_JSON_VALUE)));

        receive(builder -> builder.endpoint(authenticationServiceClient) //
                .message(new HttpMessage() //
                        .status(HttpStatus.OK)) //
                .messageType(MessageType.JSON) //
                .extractFromPayload("$.access_token", "${accessTokenValue}"));

    }
}
```

Here is BeforeTest which applies above behavior:
```
public class BeforeTest extends TestRunnerBeforeTestSupport  {

    @Autowired
    private HttpClient authenticationServiceClient;

    @Override
    public void beforeTest(final TestRunner runner) {
        runner.echo("This action should be executed before suite");

        runner.applyBehavior(new AuthenticationBehavior(authenticationServiceClient));
        runner.echo("Access Token: ${accessTokenValue}");
    }
}
```

The accessToken variable should be available in my test case, but it gives "unknown variable" exception.

```
public class AddCategoryIT extends JUnit4CitrusTestRunner {
    @Test
    @CitrusTest
    public void shouldAddResourceStatus(@CitrusResource TestContext context) throws Exception {
        author("Nimra Inam");
        description("some description");
        echo("My access token: ${token}");
    }
}

````
 
Got following exception:
```
com.consol.citrus.exceptions.CitrusRuntimeException: Unknown variable 'accessTokenValue'
	at com.consol.citrus.context.TestContext.getVariableObject(TestContext.java:158)
	at com.consol.citrus.context.TestContext.getVariable(TestContext.java:133)
	at com.consol.citrus.context.TestContext.getVariable(TestContext.java:122)
	at com.consol.citrus.variable.VariableUtils.replaceVariablesInString(VariableUtils.java:175)
	at com.consol.citrus.context.TestContext.replaceDynamicContentInString(TestContext.java:326)
	at com.consol.citrus.context.TestContext.replaceDynamicContentInString(TestContext.java:311)
	at com.consol.citrus.actions.EchoAction.doExecute(EchoAction.java:51)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.TestCase.executeAction(TestCase.java:229)
	at com.consol.citrus.dsl.runner.DefaultTestRunner.run(DefaultTestRunner.java:198)
	at com.consol.citrus.dsl.runner.DefaultTestRunner.echo(DefaultTestRunner.java:237)
	at com.consol.citrus.dsl.junit.JUnit4CitrusTestRunner.echo(JUnit4CitrusTestRunner.java:156)
	at com.etilize.burraq.category.AddCategoryIT.shouldAddCategoryWithActiveStatus(AddCategoryIT.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
	at com.consol.citrus.dsl.junit.JUnit4CitrusTest.invokeTestMethod(JUnit4CitrusTest.java:96)
	at com.consol.citrus.dsl.junit.JUnit4CitrusTest.run(JUnit4CitrusTest.java:71)
	at com.consol.citrus.junit.CitrusJUnit4Runner$InvokeRunMethod.evaluate(CitrusJUnit4Runner.java:212)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by svettwer** [comment]
I just found #400, that will implement the requested feature. Therefore I'll close this issue.
