### ISSUE TITLE
Selenium can`t find driver for browser.

### ISSUE THREAD

**Issue by NShpakov** [citrusframework/citrus#464]
**Citrus Version**
<citrus.version>RELEASE</citrus.version>
Hi! I can not to start browser by selenium. In the class EndpointConfig I wrote:

    @Bean
    public SeleniumBrowser browser() {
        return CitrusEndpoints.selenium()
                .browser()
                .type(BrowserType.CHROME)
                .webDriver(new ChromeDriver())
                .build();

In the testclass I wrote: 

    selenium()
                .browser(browser)
                .start();

I also added dependency for selenium. I want to see how chrome will be started, but I see only exception: 

```
[INFO] Download storage location is: C:\Users\N190E~1.SHP\AppData\Local\Temp\selenium8475073510786368762
[WARN] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'browser' defined in class path resource [com/temafon/partners_programm/tests/Endpointconfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.consol.citrus.selenium.endpoint.SeleniumBrowser]: Factory method 'browser' threw exception; nested exception is java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
[DEBUG] Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@3aee3976: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,citrusSpringConfig,com.consol.citrus.functions.FunctionConfig,functionRegistry,environmentPropertyFunction,citrusFunctionLibrary,com.consol.citrus.validation.matcher.ValidationMatcherConfig,matchesPath,hamcrestValidationMatcher,validationMatcherRegistry,xmlValidationMatcher,citrusValidationMatcherLibrary,com.consol.citrus.validation.MessageValidatorConfig,defaultXmlMessageValidator,defaultMessageHeaderValidator,defaultXpathMessageValidator,defaultJsonMessageValidator,defaultJsonPathMessageValidator,defaultPlaintextMessageValidator,defaultBinaryMessageValidator,defaultBinaryBase64MessageValidator,defaultGzipBinaryBase64MessageValidator,defaultXhtmlMessageValidator,defaultXhtmlXpathMessageValidator,defaultGroovyXmlMessageValidator,defaultGroovyJsonMessageValidator,defaultGroovyTextMessageValidator,citrusMessageValidatorRegistry,testContextFactory,endpointFactory,referenceResolver,globalMessageConstructionInterceptors,loggingReporter,htmlReporter,junitReporter,testListeners,testActionListeners,testSuiteListeners,messageListeners,failureStackTestListener,org.springframework.context.support.PropertySourcesPlaceholderConfigurer#0,schemaRepository,globalVariables,com.temafon.partners_programm.tests.Endpointconfig,browser,dataSource,todoClient,namespaceContextBuilder]; root of factory hierarchy
[ERROR] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@2d7275fc] to prepare test instance [com.temafon.partners_programm.tests.Test_1IT@747ddf94]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124) ~[spring-test-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83) ~[spring-test-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117) ~[spring-test-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83) ~[spring-test-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230) ~[spring-test-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:149) [spring-test-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) [testng-6.14.3.jar:na]
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59) [testng-6.14.3.jar:na]
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458) [testng-6.14.3.jar:na]
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222) [testng-6.14.3.jar:na]
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142) [testng-6.14.3.jar:na]
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168) [testng-6.14.3.jar:na]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105) [testng-6.14.3.jar:na]
	at org.testng.TestRunner.privateRun(TestRunner.java:648) [testng-6.14.3.jar:na]
	at org.testng.TestRunner.run(TestRunner.java:505) [testng-6.14.3.jar:na]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) [testng-6.14.3.jar:na]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450) [testng-6.14.3.jar:na]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415) [testng-6.14.3.jar:na]
	at org.testng.SuiteRunner.run(SuiteRunner.java:364) [testng-6.14.3.jar:na]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.14.3.jar:na]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) [testng-6.14.3.jar:na]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) [testng-6.14.3.jar:na]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) [testng-6.14.3.jar:na]
	at org.testng.TestNG.runSuites(TestNG.java:1049) [testng-6.14.3.jar:na]
	at org.testng.TestNG.run(TestNG.java:1017) [testng-6.14.3.jar:na]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72) [testng-plugin.jar:na]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'browser' defined in class path resource [com/temafon/partners_programm/tests/Endpointconfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.consol.citrus.selenium.endpoint.SeleniumBrowser]: Factory method 'browser' threw exception; nested exception is java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:128) ~[spring-test-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60) ~[spring-test-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:106) ~[spring-test-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:249) ~[spring-test-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98) ~[spring-test-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116) ~[spring-test-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	... 30 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.consol.citrus.selenium.endpoint.SeleniumBrowser]: Factory method 'browser' threw exception; nested exception is java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	... 47 common frames omitted
Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	at com.google.common.base.Preconditions.checkState(Preconditions.java:754) ~[guava-23.0.jar:na]
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:124) ~[selenium-remote-driver-3.6.0.jar:na]
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32) ~[selenium-chrome-driver-3.6.0.jar:na]
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137) ~[selenium-chrome-driver-3.6.0.jar:na]
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:329) ~[selenium-remote-driver-3.6.0.jar:na]
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88) ~[selenium-chrome-driver-3.6.0.jar:na]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123) ~[selenium-chrome-driver-3.6.0.jar:na]
	at com.temafon.partners_programm.tests.Endpointconfig.browser(Endpointconfig.java:28) ~[test-classes/:na]
	at com.temafon.partners_programm.tests.Endpointconfig$$EnhancerBySpringCGLIB$$847f31d3.CGLIB$browser$3(<generated>) ~[test-classes/:na]
	at com.temafon.partners_programm.tests.Endpointconfig$$EnhancerBySpringCGLIB$$847f31d3$$FastClassBySpringCGLIB$$3407b1a1.invoke(<generated>) ~[test-classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at com.temafon.partners_programm.tests.Endpointconfig$$EnhancerBySpringCGLIB$$847f31d3.browser(<generated>) ~[test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	... 48 common frames omitted

java.lang.IllegalStateException: Failed to load ApplicationContext

	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
```

**Comment by NShpakov** [comment]
Thank you much!

**Comment by christophd** [comment]
Welcome!

**Comment by NShpakov** [comment]
Now I have a new problem:
My browser was started,but method navigate doesn`t work... 
` @Test(priority = 1)
    @CitrusTest
    public void simple_request()  {

        selenium()
                .browser(browser).start()
               ;
        selenium()
                .browser(browser).navigate("www.ru")
                ;`
Error in the log:
`[DEBUG] Connection released: [id: 0][route: {}->http://localhost:39270][total kept alive: 1; route allocated: 1 of 2000; total allocated: 1 of 2000]
[INFO] 
[ERROR] TEST FAILED Test_1IT.simple_request <com.temafon.partners_programm.tests> Nested exception is: 
com.consol.citrus.exceptions.CitrusRuntimeException: Failed to create relative page URL - must set start page on browser
	at com.consol.citrus.selenium.actions.NavigateAction.execute(NavigateAction.java:73) ~[citrus-selenium-2.7.6.jar:na]
	at com.consol.citrus.selenium.actions.AbstractSeleniumAction.doExecute(AbstractSeleniumAction.java:58) ~[citrus-selenium-2.7.6.jar:na]
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:46) [citrus-core-2.7.6.jar:na]
	at com.consol.citrus.dsl.actions.DelegatingTestAction.doExecute(DelegatingTestAction.java:54) ~[citrus-java-dsl-2.7.6.jar:na]
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:46) [citrus-core-2.7.6.jar:na]
	at com.consol.citrus.TestCase.executeAction(TestCase.java:234) ~[citrus-core-2.7.6.jar:na]
	at com.consol.citrus.TestCase.doExecute(TestCase.java:153) ~[citrus-core-2.7.6.jar:na]
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:46) [citrus-core-2.7.6.jar:na]
	at com.consol.citrus.Citrus.run(Citrus.java:403) [citrus-core-2.7.6.jar:na]
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.invokeTestMethod(TestNGCitrusTest.java:125) [citrus-java-dsl-2.7.6.jar:na]
	at com.consol.citrus.dsl.testng.TestNGCitrusTestDesigner.invokeTestMethod(TestNGCitrusTestDesigner.java:73) [citrus-java-dsl-2.7.6.jar:na]`

**Comment by NShpakov** [comment]
If I wrote like this:
`        selenium()
                .browser(browser).navigate(todoClient.getEndpointConfiguration().getRequestUrl() + "/value")
                ;`. It will be work.

**Comment by NShpakov** [comment]
I have global variable ` variables.getVariables().put("path_fotoflirt","/service/fotoflirt");`. I want to use this code: `selenium()
                .browser(browser).navigate(todoClient.getEndpointConfiguration().getRequestUrl() + "${path_fotoflirt}")
                ;`
It also does not work...

**Comment by NShpakov** [comment]
Maybe in the method navigate will be better use type String and variables from testcontext?
