### ISSUE TITLE
Cucumber+Citrus: Running tests in parallel 

### ISSUE THREAD

**Issue by natasha4** [citrusframework/citrus#487]
Citrus Version: 2.7.4

In out project we are using Cucumber BDD to write scenarios in feature files. And now we are looking for approach to run them in parallel.  

Our approach was to generate a cucumber runner per a feature file and then run these runners using jUnit in parallel. (for example, using https://github.com/temyers/cucumber-jvm-parallel-plugin)
When I tried to do so I got an exception for the second runner:

`
java.lang.IllegalStateException: Unable to initialize Citrus instance - instance has already been initialized

	at cucumber.runtime.java.CitrusBackend.initializeCitrus(CitrusBackend.java:138)
	at cucumber.runtime.java.spring.CitrusSpringObjectFactory.getInstance(CitrusSpringObjectFactory.java:109)
	at cucumber.runtime.java.spring.CitrusSpringObjectFactory.start(CitrusSpringObjectFactory.java:88)
	at cucumber.runtime.java.JavaBackend.buildWorld(JavaBackend.java:123)
	at cucumber.runtime.Runtime.buildBackendWorlds(Runtime.java:141)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:38)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	...
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
	...
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
	...
`

It seems that it's impossible to have several runners

Do you have any idea how to run test in parallel in this case?

Thank you!

**Comment by christophd** [comment]
Can you please try with Citrus v2.7.7. https://github.com/citrusframework/citrus/issues/357 has been fixed in v2.7.5 and seems to be related to your issue.

**Comment by natasha4** [comment]
Thanks a lot for a quick response! 
The bug description looks exactly as a problem I have. I will update citrus version and check how it works. I will give update as soon as I check it.

Thank you!

**Comment by natasha4** [comment]
the issue is fixed by updating to the version 2.7.7
