### ISSUE TITLE
I can not to use value of variable from the Endpointconfig.class and BeforeTest.class

### ISSUE THREAD

**Issue by NShpakov** [citrusframework/citrus#496]
**Citrus Version**
2.7.7

**Expected behavior**
I expected that value of my variable will be known.

**Actual behavior**
```14:28:42,199 ERROR port.LoggingReporter| TEST FAILED BookShelf.test_4 <com.temafon.x.x> Nested exception is: 
com.consol.citrus.exceptions.CitrusRuntimeException: Unknown variable 'randomstring'
	at com.consol.citrus.context.TestContext.getVariableObject(TestContext.java:158)
	at com.consol.citrus.context.TestContext.getVariable(TestContext.java:133)
	at com.consol.citrus.context.TestContext.getVariable(TestContext.java:122)
	at com.consol.citrus.variable.VariableUtils.replaceVariablesInString(VariableUtils.java:175)
	at com.consol.citrus.context.TestContext.replaceDynamicContentInString(TestContext.java:346)
	at com.consol.citrus.context.TestContext.replaceDynamicContentInString(TestContext.java:331)
	at com.consol.citrus.validation.builder.StaticMessageContentBuilder.buildMessagePayload(StaticMessageContentBuilder.java:48)
	at com.consol.citrus.validation.builder.AbstractMessageContentBuilder.buildMessageContent(AbstractMessageContentBuilder.java:83)
	at com.consol.citrus.http.message.HttpMessageContentBuilder.buildMessageContent(HttpMessageContentBuilder.java:57)
	at com.consol.citrus.actions.SendMessageAction.createMessage(SendMessageAction.java:163)
	at com.consol.citrus.actions.SendMessageAction.doExecute(SendMessageAction.java:90)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.dsl.actions.DelegatingTestAction.doExecute(DelegatingTestAction.java:54)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.TestCase.executeAction(TestCase.java:234)
	at com.consol.citrus.TestCase.doExecute(TestCase.java:153)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.Citrus.run(Citrus.java:403)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.invokeTestMethod(TestNGCitrusTest.java:125)
	at com.consol.citrus.dsl.testng.TestNGCitrusTestDesigner.invokeTestMethod(TestNGCitrusTestDesigner.java:73)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.run(TestNGCitrusTest.java:110)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.run(TestNGCitrusTest.java:56)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
14:28:42,201 INFO  port.LoggingReporter| ------------------------------------------------------------------------
14:28:42,201 INFO  port.LoggingReporter| 

com.consol.citrus.exceptions.TestCaseFailedException: Unknown variable 'randomstring'
14:28:42,199 ERROR port.LoggingReporter| TEST FAILED BookShelf.test_4 <com.temafon.x.x> Nested exception is: 
com.consol.citrus.exceptions.CitrusRuntimeException: Unknown variable 'randomstring'
	at com.consol.citrus.context.TestContext.getVariableObject(TestContext.java:158)
	at com.consol.citrus.context.TestContext.getVariable(TestContext.java:133)
	at com.consol.citrus.context.TestContext.getVariable(TestContext.java:122)
	at com.consol.citrus.variable.VariableUtils.replaceVariablesInString(VariableUtils.java:175)
	at com.consol.citrus.context.TestContext.replaceDynamicContentInString(TestContext.java:346)
	at com.consol.citrus.context.TestContext.replaceDynamicContentInString(TestContext.java:331)
	at com.consol.citrus.validation.builder.StaticMessageContentBuilder.buildMessagePayload(StaticMessageContentBuilder.java:48)
	at com.consol.citrus.validation.builder.AbstractMessageContentBuilder.buildMessageContent(AbstractMessageContentBuilder.java:83)
	at com.consol.citrus.http.message.HttpMessageContentBuilder.buildMessageContent(HttpMessageContentBuilder.java:57)
	at com.consol.citrus.actions.SendMessageAction.createMessage(SendMessageAction.java:163)
	at com.consol.citrus.actions.SendMessageAction.doExecute(SendMessageAction.java:90)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.dsl.actions.DelegatingTestAction.doExecute(DelegatingTestAction.java:54)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.TestCase.executeAction(TestCase.java:234)
	at com.consol.citrus.TestCase.doExecute(TestCase.java:153)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.Citrus.run(Citrus.java:403)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.invokeTestMethod(TestNGCitrusTest.java:125)
	at com.consol.citrus.dsl.testng.TestNGCitrusTestDesigner.invokeTestMethod(TestNGCitrusTestDesigner.java:73)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.run(TestNGCitrusTest.java:110)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.run(TestNGCitrusTest.java:56)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
14:28:42,201 INFO  port.LoggingReporter| ------------------------------------------------------------------------
14:28:42,201 INFO  port.LoggingReporter| 

com.consol.citrus.exceptions.TestCaseFailedException: Unknown variable 'randomstring'
```

**Test case sample**
I use this test : `    @CitrusTest
    @Test(enabled = true)
    public void test_4(){
        description("GET /shelf/{shelf_id}");
        status(TestCaseMetaInfo.Status.DRAFT);

        http().client(todoclient).send().put("/shelf/${shelf_id}")
                .header("Content-type", "application/json")
                .header("X-User-Token","${token}").payload(new ClassPathResource("templates/put_shelf_shelfID.json"))
        ;
        http().client(todoclient).receive()
                .response(HttpStatus.OK).messageType(MessageType.JSON)
        ;
    }`
This is my json file: '''{
  "type" : "citrus:randomEnumValue('default', 'favorite', 'recommended')",
  "title" : "citrus:concat('title', citrus:randomNumber(10))",
  "notes" : "citrus:concat('notes is: ', ${randomstring})",
  "is_public" : citrus:randomEnumValue('true', 'false'),
  "books" : [ ${book_id},  2125749,  1876378,  1864993 ]
}'''
This is my variable in BeforeTest.class :
'disigner.variable("randomstring","citrus:randomString(10, MIXED)");'
And this is my bean in the Endpointconfig.class `    @Bean
    public GlobalVariables globalVariables()
    {
        GlobalVariables variables = new GlobalVariables();
        // Vars for tests
        variables.getVariables().put("randomstring","citrus:randomString(10, MIXED)");

        return variables;
    }`

I can not to use value of variable from the Endpointconfig.class and BeforeTest.class. I will see value of variable only like this : ```    @CitrusTest
    @Test(enabled = false)
    public void test_1(){

        description("POST /user/shelf/new");
        status(TestCaseMetaInfo.Status.DRAFT);
variable("randomstring","citrus:randomString(10, MIXED)");

        http().client(todoclient).send().post("/shelf/new")
                .header("Content-type", "application/json")
                .header("X-User-Token","${token}")
                .payload(new ClassPathResource("templates/post_user_shelfs_new.json"));

        http().client(todoclient).receive()
                .response(HttpStatus.OK).messageType(MessageType.JSON)
        ;```

**Comment by christophd** [comment]
Setting the variable in `BeforeTest.class` will not work for a good reason. The test is not sharing the test variables with before test classes. This is a limitation by design as we do not want to influence all tests with a single before test class.

But putting the global variables bean to the `EndpointConfig.class` as Spring bean should work. I tried this in a small sample project and it works fine.

```java
@Bean
public GlobalVariables globalVariables() {
    GlobalVariables variables = new GlobalVariables();
    variables.getVariables().put("randomstring","citrus:randomString(10, MIXED)");
    return variables;
}
```

```java
@Test
@CitrusTest
public void testGlobalVariable() {
    echo("Variable value: ${randomstring}");
}
```

```
DEBUG com.consol.citrus.TestCase - Global variables:
DEBUG com.consol.citrus.TestCase - randomstring = citrus:randomString(10, MIXED)
...
com.consol.citrus.TestCase - Test variables:
DEBUG com.consol.citrus.TestCase - randomstring = citrus:randomString(10, MIXED)
...
TEST STEP 1/5: echo
INFO com.consol.citrus.actions.EchoAction - Variable value: aplPysEQEc
```

So please remove variable creation in `BeforeTest.class` and double check that it is not working for you. In case it is not working please provide detailed test project setup and log stack trace information.

**Comment by svettwer** [comment]
Hi!

Concerning the` Endpointconfig.class`:
I've tested your setup locally and it works as expected.
Do you have a citrus-application.properties file in your resource folder containing the class path of your endpoint config? E.g. `citrus.spring.java.config=com.consol.citrus.samples.todolist.EndpointConfig`

Concerning your `BeforeTest.class`: 
If you're using a  `TestDesignerBeforeTestSupport` or a `TestDesignerBeforeSuiteSupport`, please notice that the context of those classes is different to the test class context so that the test variables are not influenced by actions that are performed before test or before suite.

BR,
Sven

**Comment by svettwer** [comment]
Ah, too slow. :+1: ;-)

**Comment by NShpakov** [comment]
Sorry for wait. I understand. It happen because I wrote the global variables in both places. First in the context.xml: `   <citrus:global-variables>
        <citrus:variable name="project.name" value="Citrus Integration Tests"/>
    </citrus:global-variables>
`
Second in the Endpointconfig.class : ``@Bean
    public GlobalVariables globalVariables()
    {
        GlobalVariables variables = new GlobalVariables();
        // Vars for tests
        variables.getVariables().put("sisdn",
                "79653594582");
        variables.getVariables().put("randomstring","citrus:randomString(10, MIXED)");
        variables.getVariables().put("random","citrus:randomString(10, MIXED)");
        variables.getVariables().put("new_var","new value");

        return variables;
    }``. I understand about design of tests. Thank you guys! Sory for my  
inattention.
