### ISSUE TITLE
Selenium Junit 5 not working as it works for TestNG

### ISSUE THREAD

**Issue by vmasule** [citrusframework/citrus#627]
**Citrus Version**
2.8.0

**Expected behavior**
Should load all the internal dependencies as it does for TestNG framework but not for Junit5 

**Actual behavior**
I am getting below error when I am trying to create test case with Junit 5 extension that use selenium hooks as given in sample selenium test case (https://github.com/citrusframework/citrus-samples/tree/master/sample-selenium/java-dsl). Getting error when creating for `after` hook.

```
 Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
 afterSuite' defined in uk.co.hitachicapital.hccf.creditdecisioning.config.CitrusConfig: Invocation of init method failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.consol.citrus.report.TestListeners' available
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:128)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:107)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:243)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 66 more

Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.consol.citrus.report.TestListeners' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:347)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:334)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1107)
	at com.consol.citrus.Citrus.<init>(Citrus.java:286)
	at com.consol.citrus.Citrus.<init>(Citrus.java:48)
	at com.consol.citrus.Citrus$CitrusInstanceManager.newInstance(Citrus.java:136)
	at com.consol.citrus.Citrus.newInstance(Citrus.java:317)
	at com.consol.citrus.dsl.runner.TestRunnerAfterSuiteSupport.afterPropertiesSet(TestRunnerAfterSuiteSupport.java:63)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1761)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1698)
	... 81 more
```

 

**Test case sample**

```
@ExtendWith(value = { CitrusExtension.class, SpringExtension.class})
@ContextConfiguration(classes = { CitrusConfig.class})
public class DecisionServiceIntegrationTest {
    @CitrusEndpoint(name = "httpRestClient")
    private HttpClient customerRestClient;

   @CitrusTest
    @Test
    void createAndValidateCustomer(@CitrusResource TestDesigner designer) {
        designer.description("Create new business partner");
        designer.creationDate(new Date());
        designer.status(TestCaseMetaInfo.Status.READY_FOR_REVIEW);
    }
}
```

And in CitrusConfig I have added

```
 @Bean
    public SeleniumBrowser browser() {
        return CitrusEndpoints.selenium()
                .browser()
                .type(BrowserType.CHROME)
                .build();
    }
     
    @Bean
    @DependsOn("browser")
    public SequenceAfterSuite afterSuite(SeleniumBrowser browser) {
        return new TestRunnerAfterSuiteSupport() {
            @Override
            public void afterSuite(TestRunner runner) {
                runner.selenium(builder -> builder.browser(browser).stop());
            }
        };
    }

    @Bean
    public SequenceAfterTest afterTest() {
        return new TestRunnerAfterTestSupport() {
            @Override
            public void afterTest(TestRunner runner) {
                runner.sleep(500);
            }
        };
    }
```

Though it works fine for TestNG but I wanted to use advance feature of Junit 5.

**Comment by svettwer** [comment]
Hi!

I'll try to reconstruct the issue as soon as possible.

BR,
Sven

**Comment by svettwer** [comment]
Hi!

Please remove the `SpringExtension.class` from your `@ExtendWith` annotation. This will fix the issue.

BR,
Sven

**Comment by vmasule** [comment]
@svettwer Well when I remove `SpringExtension.class` then `@Autowired` doesn't work. Is there a extension class for Junit 5 as it is for Junit4 & TestNG?

**Comment by svettwer** [comment]
Hi @vmasule!

No, there is no such an extension for Junit 5. Im a little bit confuse as there is no `@Autowired` annotation in your provided code. Please use the `@CitrusEndpoint` Annotation for injecting Citrus endpoints with Junit 5 test cases.

The [Junit 5 sample](https://github.com/citrusframework/citrus-samples/tree/master/samples-junit/sample-junit5) of the citrus-samples repository might help you.

BR,
Sven

**Comment by svettwer** [comment]
Closed due to inactivity.

**Comment by Ivan-Polkovnikov-94** [comment]
Hi! 

I have similar problem. I have some custom beans in my CitrusConfig and I want to use it with @Autowired in my test classes, is it possible?

**Comment by bbortt** [comment]
I think it's possible. are you struggling to do so? please open a new issue if you do so, this one has already been closed.
