### ISSUE TITLE
Long delay between consuming kafka topics for validation

### ISSUE THREAD

**Issue by joel-costigliola** [citrusframework/citrus#724]
**Citrus Version**

2.8.0

**Question**

I'm experiencing in my test a 5min delay between kafka topics consumption, I was wondering if there is a parameter to control that. Any guidance would be appreciated.

Here's what my test looks like:
```java
// Given a message to send
JsonNode newMessage = MAPPER.readTree(FileUtils.getFile("src", "test", "resources", "input", "svof_new_msg.json"));

// When I send the message
designer.send(INPUT_ENDPOINT)
    .header(KafkaMessageHeaders.MESSAGE_KEY, newMessage.get("flightIdConcatenated").asText(""))
    .messageType(MessageType.PLAINTEXT)
    .payload(newMessage.toString());

// then the message is processed in two different ways, each result is sent to different topics
// checking the first output topic 
designer.receive(AIDX_FLIGHT_RECORD_OUTPUT_ENDPOINT)
    .timeout(DEFAULT_TIMEOUT) // 10 min!
    .messageType(MessageType.BINARY)
    .validator(new NewMessageValidatorForOldTopic());
// checking the second topic
designer.receive(AIDX_FLIGHT_RECORD_CHANGED_EVENTS_OUTPUT_ENDPOINT)
    .timeout(DEFAULT_TIMEOUT)
    .messageType(MessageType.BINARY)
    .validator(new NewMessageValidatorForNewTopic());
```

the first `receive` occurs relatively fast (~10seconds) as per the log extract below
```
2020-06-10 12:09:06,395 32359 DEBUG [main] [] c.c.c.k.e.KafkaProducer - Sending Kafka stream message to topic: '_svof_delta-event-v0'
2020-06-10 12:09:06,431 32395 INFO [main] [] c.c.c.k.e.KafkaProducer - Message was sent to Kafka stream topic: '_svof_delta-event-v0'
2020-06-10 12:09:06,431 32395 DEBUG [main] [] L.Message_OUT - DEFAULTMESSAGE ... not printing the message as it is long and irrelevant
...
// this is my app processing the message sent in the input topic 
2020-06-10 12:09:18,434 44398 INFO [_aidx_flight-record-out-transformer-3d48c1e2-8f0e-4fff-acfa-04725c1ecd52-StreamThread-1] [] n.c.a.a.a.f.n.t.t.AidxTransformTopology - Event for flight QQ_0352_01Mar2019GTS received.
...
2020-06-10 12:09:18,897 44861 INFO [_aidx_flight-record-out-transformer-3d48c1e2-8f0e-4fff-acfa-04725c1ecd52-StreamThread-1] [] n.c.a.a.a.f.n.t.t.AidxTransformTopology - Finished processing message key QQ_0352_01Mar2019GTS
```
it is validated successfully ~1s later
```
2020-06-10 12:09:18,933 44897 DEBUG [main] [] i.c.k.s.c.r.RestService - Sending GET with input null to http://localhost:8081/schemas/ids/4
2020-06-10 12:09:18,966 44930 DEBUG [main] [] c.c.c.k.e.KafkaConsumer - Received message: (QQ_0352_01Mar2019GTS .... too long
2020-06-10 12:09:18,968 44932 WARN [main] [] c.c.c.u.TypeConversionUtils - Using object toString representation: Failed to convert value of type 'nz.co.airnz.ao.aidx.flight.record.changed.event.model.AidxFlightRecordChangedEventEnvelope' to required type 'java.lang.String'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'nz.co.airnz.ao.aidx.flight.record.changed.event.model.AidxFlightRecordChangedEventEnvelope' to required type 'java.lang.String': no matching editors or conversion strategy found
2020-06-10 12:09:18,968 44932 DEBUG [main] [] L.Message_IN - KAFKAMESSAGE [id: bf02960a-a6f8-49d2-8487-32d537e78932, payload: ... 
2020-06-10 12:09:18,972 44936 INFO [main] [] c.c.c.k.e.KafkaConsumer - Received Kafka message on topic: 'aidx.AidxFlightRecordChangedEvents.v0
2020-06-10 12:09:19,171 45135 DEBUG [main] [] c.c.c.v.DefaultMessageHeaderValidator - Start message header validation ...
2020-06-10 12:09:19,172 45136 INFO [main] [] c.c.c.v.DefaultMessageHeaderValidator - Message header validation successful: All values OK
2020-06-10 12:09:19,172 45136 INFO [main] [] c.c.c.r.LoggingReporter - 
2020-06-10 12:09:19,172 45136 DEBUG [main] [] c.c.c.r.LoggingReporter - TEST STEP 2/3 SUCCESS
2020-06-10 12:09:19,172 45136 INFO [main] [] c.c.c.r.LoggingReporter - 
2020-06-10 12:09:19,172 45136 DEBUG [main] [] c.c.c.r.LoggingReporter - TEST STEP 3/3: receive
```

At this point everything is fine, but the next `receive` is only triggered 5min later, note the jump from `12:09:19,174` to `12:14:19,215` in:
```
2020-06-10 12:09:19,174 45138 WARN [main] [] o.a.k.c.c.ConsumerConfig - The configuration 'auto.register.schemas' was supplied but isn't a known config.
2020-06-10 12:09:19,174 45138 DEBUG [main] [] c.c.c.k.e.KafkaConsumer - Receiving Kafka message on topic: '_aidx_flight-leg-notif-rq-event-out-v0
2020-06-10 12:14:19,215 345179 DEBUG [main] [] i.c.k.s.c.r.RestService - Sending GET with input null to http://localhost:8081/schemas/ids/3
2020-06-10 12:14:19,223 345187 DEBUG [main] [] c.c.c.k.e.KafkaConsumer - Received message: (QQ_0352_01Mar2019GTS, ... 
...
2020-06-10 12:14:19,228 345192 INFO [main] [] c.c.c.k.e.KafkaConsumer - Received Kafka message on topic: '_aidx_flight-leg-notif-rq-event-out-v0
2020-06-10 12:14:19,289 345253 DEBUG [main] [] c.c.c.v.DefaultMessageHeaderValidator - Start message header validation ...
2020-06-10 12:14:19,289 345253 INFO [main] [] c.c.c.v.DefaultMessageHeaderValidator - Message header validation successful: All values OK
2020-06-10 12:14:19,289 345253 INFO [main] [] c.c.c.r.LoggingReporter - 
2020-06-10 12:14:19,289 345253 DEBUG [main] [] c.c.c.r.LoggingReporter - TEST STEP 3/3 SUCCESS
2020-06-10 12:14:19,394 345358 INFO [main] [] c.c.c.r.LoggingReporter - 
2020-06-10 12:14:19,395 345359 INFO [main] [] c.c.c.r.LoggingReporter - TEST SUCCESS AidxFlightRecordTransformAppTest.testServiceForNewMessage (nz.co.airnz.ao.aidx.flightleg.notifrq.integration)
```

Full logs: [logs.txt](https://github.com/citrusframework/citrus/files/4756440/logs.txt)

**What I've tried so far**

Increasing the time out to 10min, the test succeeds but is flaky I had this exception a few times:

```
org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:871)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:821)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:894)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:874)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:204)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:167)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:127)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:586)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:400)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:303)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:218)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:692)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1334)
	at com.consol.citrus.kafka.endpoint.KafkaConsumer.receive(KafkaConsumer.java:86)
	at com.consol.citrus.actions.ReceiveMessageAction.receive(ReceiveMessageAction.java:140)
	at com.consol.citrus.actions.ReceiveMessageAction.doExecute(ReceiveMessageAction.java:120)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.dsl.actions.DelegatingTestAction.doExecute(DelegatingTestAction.java:54)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.TestCase.executeAction(TestCase.java:220)
	at com.consol.citrus.TestCase.doExecute(TestCase.java:152)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.Citrus.run(Citrus.java:403)
	at com.consol.citrus.dsl.junit.jupiter.CitrusExtension.afterTestExecution(CitrusExtension.java:75)
```

I have tried building my endpoint synchronous and asynchronous but did not see any differences related to that delay.

I have inverted the order of my two `receive` operations, it is always the second receive that is delayed, moreover the delay is always 5min.

I can also confirm that the processed messages are send at almost  the same time in the two kafka output topic, I verified that in a local kafka admin UI so the delay is not due to the second message arriving late in the second topic. 

**Additional information**

The output endpoint are built like that:
```java
    Map<String, Object> configMap = new HashMap<>();
    configMap.put(AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, "http://localhost:8081");
    configMap.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
    configMap.put(AbstractKafkaAvroSerDeConfig.AUTO_REGISTER_SCHEMAS, false);
    SpecificAvroSerde<AidxFlightRecord> valueSpecificAvroSerde = initAidxFlightRecordAvroSerde(configMap);
    // keep track of serdes to close them
    serdes.add(valueSpecificAvroSerde);
    return CitrusEndpoints.kafka()
        .asynchronous()
        .server(CONFIG.getBootstrapServerHost() + ":" + CONFIG.getBootstrapServerPort())
        .topic(CONFIG.getAidxFlightLegNotifRQOutputTopic())
        .offsetReset(offsetReset)
        .consumerProperties(configMap)
        .keyDeserializer(StringDeserializer.class)
        .valueDeserializer(valueSpecificAvroSerde.deserializer().getClass())
        .timeout(DEFAULT_TIMEOUT)
        .build();
```

Environment:
```
Gradle 5.2.1

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.4 (Amazon.com Inc. 11.0.4+11-LTS)
OS:           Windows 10 10.0 amd64
```

I hope I have given enough information, happy to provide more if that helps

**Comment by joel-costigliola** [comment]
The actual issue was that I did not set different consumer group for the different kafka enpoint that were validating the two output topics.
I can't explain exactly why it led to time out but that was the root cause.

One thing citrus might want to consider is to explicitly require a consumer group to be set.
