### ISSUE TITLE
Random concurrent modification exception when receiving message from http channel

### ISSUE THREAD

**Issue by ZuikovAV** [citrusframework/citrus#732]
**2.7.4**

**Message always received from http channel**

**Concurrent Modification Exception is randomly reproduced**

Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
	at java.util.AbstractMap.toString(AbstractMap.java:554)
	at java.util.Collections$UnmodifiableMap.toString(Collections.java:1495)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.consol.citrus.message.DefaultMessage.toString(DefaultMessage.java:104)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.springframework.messaging.support.GenericMessage.toString(GenericMessage.java:111)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:432)

**Comment by christophd** [comment]
are you having the same issue with 2.8.0? or 3.0.0.M1?

**Comment by ZuikovAV** [comment]
Yes, i have the same at 2.8.0. At 3.0.0.M1 can't say - have'nt worked it with it yet.

**Comment by ZuikovAV** [comment]
Hi! Tell me please is the problem solved?

**Comment by christophd** [comment]
Is there a specific test setup that reproduces the error? Even if it occurs randomly it might be good to know which setup is used to receive the Http message.

Also please consider to move forward to 3.0.0-M3 as the 2.x release train is not likely to get much attention anymore

**Comment by ZuikovAV** [comment]
Is 3.0 ready? I found no info at official site. 

I'll try to reproduce and return with the results.

**Comment by ZuikovAV** [comment]
I suppose i found the problem. If .messageType is not present in the response from http-server (JSON type in this case expected), citrus peridocially recognizes message type as XML.

**Comment by ZuikovAV** [comment]
The problem is not with message type...

**Comment by ZuikovAV** [comment]
> Is there a specific test setup that reproduces the error? Even if it occurs randomly it might be good to know which setup is used to receive the Http message.
> 
> Also please consider to move forward to 3.0.0-M3 as the 2.x release train is not likely to get much attention anymore

Hi. If client or server is meant by setup - i got this problem only when get messages from http-server.
