### ISSUE TITLE
jdbcServer - httpServer - citrus - cucumber - spring : Timeout exception

### ISSUE THREAD

**Issue by ankitrlps** [citrusframework/citrus#756]
Citrus version: 2.8.0
Citrus JDBC version: 3.0.0-M2
Citrus DB version: 0.1.4
Spring version: 2.1.6

The application has endpoint that executes the stored procedure into Oracle DB. 
So I have test scenarios in feature file of cucumber with @given, @when and @then format. In the @given method, I am trying to open connection, receive stored proc call and send the success response. In @when, I am sending a http post request. And in @then, I am receiving a 200 response.

Now I run the cucumber test runner and it always throws timeout exception even when I increase the timeout of jdbcserver and httpClient.

My configs:
```
public class CitrusConfigs {
@Bean
    @Lazy
    public HttpClient httpClient(@LocalServerPort int randomServerPort) {
        return CitrusEndpoints.http().client()
                .requestUrl(String.format("%s:%s", "http://localhost", randomServerPort))
                //.timeout(5000L)
                //.contentType(MediaType.APPLICATION_JSON_VALUE)
                .build();
    }

@Bean
    public SingleConnectionDataSource dataSource() {
        SingleConnectionDataSource dataSource = new SingleConnectionDataSource();
        dataSource.setDriverClassName(JdbcDriver.class.getName());
        dataSource.setUrl(String.format("jdbc:citrus:http://%s:%s/%s", HOST_NAME, SERVER_PORT, DATABASE_NAME));
        dataSource.setUsername("sa");
        dataSource.setPassword("");
        return dataSource;
    }

    @Bean
    public JdbcServer jdbcServer() {
        return CitrusEndpoints.jdbc().server()
                .host(HOST_NAME)
                .databaseName(DATABASE_NAME)
                .port(SERVER_PORT)
                //.timeout(10000L)
                .autoStart(true)
                .autoConnect(false)
                .autoCreateStatement(false)
                .build();
    }
}
```

```
@SpringBootTest(classes = EnvCitrusConfig.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class TestClass {

    @Autowired
    private TestRunner testRunner;

    @Autowired
    private HttpClient httpClient;

    @Autowired
    private JdbcServer jdbcServer;

    @Given("something here from feature file scenario")
    public void mock_jdbc_server_environment_table() {

        testRunner.receive(k -> k.endpoint(jdbcServer).message(JdbcMessage.openConnection()));
        testRunner.receive(receiveMessageBuilder -> receiveMessageBuilder.endpoint(jdbcServer).message(JdbcMessage.createCallableStatement("{CALL testproccall(?)}")));
        testRunner.send(sendMessageBuilder -> sendMessageBuilder.endpoint(jdbcServer).messageType(MessageType.JSON).message(JdbcMessage.success()));
        testRunner.receive(r -> r.endpoint(jdbcServer).message(JdbcMessage.closeStatement()));
        testRunner.receive(r -> r.endpoint(jdbcServer).message(JdbcMessage.closeConnection()));
    }

    @When("hitting an endpoint with {string} and {string}")
    public void get_call_for_environment(String path, String payloadLocation) {
        testRunner.http(httpActionBuilder ->
                httpActionBuilder
                        .client(httpClient)
                        .send()
                        .post(path)
                        .messageType(MessageType.JSON)
                        .contentType(ContentType.APPLICATION_JSON.toString())
                        .payload(new ClassPathResource(String.format("/test-jsons/%s", payloadLocation))));
    }

    @Then("the endpoint must return {string}")
    public void after_running_stored_procedures(String result) {
        testRunner.http(httpActionBuilder ->
                httpActionBuilder
                        .client(httpClient)
                        .receive()
                        .response(HttpStatus.OK)
                        .statusCode(200)
                        .payload(result));
    }
}
```

**Error:**
```
11:52:08.637 INFO  o.s.s.w.DefaultSecurityFilterChain| Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@600b3bee, org.springframework.security.web.context.SecurityContextPersistenceFilter@be186df, org.springframework.security.web.header.HeaderWriterFilter@7d12fb85, org.springframework.security.web.authentication.logout.LogoutFilter@2148849f, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@2c257c0a, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@4a225014, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@129348e8, org.springframework.security.web.session.SessionManagementFilter@3eb8057c, org.springframework.security.web.access.ExceptionTranslationFilter@497c1d78, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@7b9b6a56]
11:52:09.211 DEBUG c.c.c.c.TestContextFactory| Created new test context - using global variables: '{}'
11:52:10.035 DEBUG c.c.c.jdbc.server.JdbcServer| Starting server: jdbcServer ...
11:52:10.196 WARN  o.e.j.server.AbstractConnector| Ignoring deprecated socket close linger time
11:52:10.198 INFO  s.e.jetty.EmbeddedJettyServer| == Spark has ignited ...
11:52:10.198 INFO  s.e.jetty.EmbeddedJettyServer| >> Listening on 0.0.0.0:3306
11:52:10.292 INFO  c.c.c.jdbc.server.JdbcServer| Started server: jdbcServer
11:52:11.044 INFO  o.s.s.c.ThreadPoolTaskExecutor| Initializing ExecutorService 'applicationTaskExecutor'
11:52:12.824 WARN  o.s.x.t.TransformerFactoryUtils| http://javax.xml.XMLConstants/property/accessExternalDTD property not supported by org.apache.xalan.processor.TransformerFactoryImpl
11:52:12.824 WARN  o.s.x.t.TransformerFactoryUtils| http://javax.xml.XMLConstants/property/accessExternalStylesheet property not supported by org.apache.xalan.processor.TransformerFactoryImpl
11:52:13.250 INFO  o.s.s.c.ThreadPoolTaskScheduler| Initializing ExecutorService 'taskScheduler'
11:52:13.449 INFO  o.s.i.e.EventDrivenConsumer| Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
11:52:13.450 INFO  o.s.i.c.PublishSubscribeChannel| Channel 'crew-environments-service.errorChannel' has 1 subscriber(s).
11:52:13.450 INFO  o.s.i.e.EventDrivenConsumer| started _org.springframework.integration.errorLogger
11:52:13.450 INFO  s.d.s.w.p.DocumentationPluginsBootstrapper| Context refreshed
11:52:13.505 INFO  s.d.s.w.p.DocumentationPluginsBootstrapper| Found 1 custom documentation plugin(s)
11:52:13.583 INFO  s.d.s.w.s.ApiListingReferenceScanner| Scanning for api listing references
11:52:13.967 INFO  o.a.c.http11.Http11NioProtocol| Starting ProtocolHandler ["http-nio-auto-1"]
11:52:14.004 INFO  o.s.b.w.e.t.TomcatWebServer| Tomcat started on port(s): 58078 (http) with context path ''
11:52:14.245 INFO  o.s.b.w.e.t.TomcatWebServer| Tomcat initialized with port(s): 0 (http)
11:52:14.246 INFO  o.a.c.http11.Http11NioProtocol| Initializing ProtocolHandler ["http-nio-auto-2"]
11:52:14.247 INFO  o.a.c.core.StandardService| Starting service [Tomcat]
11:52:14.247 INFO  o.a.c.core.StandardEngine| Starting Servlet engine: [Apache Tomcat/9.0.21]
11:52:14.319 INFO  o.a.c.c.C.[.[localhost].[/]| Initializing Spring embedded WebApplicationContext
11:52:14.319 INFO  o.s.web.context.ContextLoader| Root WebApplicationContext: initialization completed in 311 ms
11:52:14.372 INFO  o.s.b.a.e.w.EndpointLinksResolver| Exposing 9 endpoint(s) beneath base path '/actuator'
11:52:14.470 INFO  o.a.c.http11.Http11NioProtocol| Starting ProtocolHandler ["http-nio-auto-2"]
11:52:14.485 INFO  o.s.b.w.e.t.TomcatWebServer| Tomcat started on port(s): 58083 (http) with context path ''
11:52:14.490 INFO  s.t.s.JdbcUpsertStepDef| Started JdbcUpsertStepDef in 17.039 seconds (JVM running for 19.635)

@Stored-Procedure-Testing
Scenario Outline: something here from feature file scenario                                             # features/UpsertOnProcedure.feature:11
11:52:16.763 INFO  c.c.c.report.LoggingReporter| 
11:52:16.764 DEBUG c.c.c.report.LoggingReporter| TEST STEP 1: receive
11:52:16.768 DEBUG c.c.c.channel.ChannelConsumer| Receiving message from: jdbcServer.inbound
  Given something here from feature file scenario # service.test.stepdefinition.JdbcUpsertStepDef.mock_jdbc_server_environment_table(java.lang.String,java.lang.String,java.lang.String)
      com.consol.citrus.exceptions.TestCaseFailedException: Action timeout while receiving message from channel 'jdbcServer.inbound'
	at com.consol.citrus.TestCase.executeAction(TestCase.java:227)
	at com.consol.citrus.dsl.runner.DefaultTestRunner.run(DefaultTestRunner.java:188)
	at com.consol.citrus.dsl.runner.DefaultTestRunner.receive(DefaultTestRunner.java:309)
	at service.test.stepdefinition.JdbcUpsertStepDef.mock_jdbc_server_environment_table(JdbcUpsertStepDef.java:60)
	at ✽.something here from feature file scenario(classpath:features/UpsertOnProcedure.feature:5)
Caused by: com.consol.citrus.exceptions.ActionTimeoutException: Action timeout while receiving message from channel 'jdbcServer.inbound'
	at com.consol.citrus.channel.ChannelConsumer.receive(ChannelConsumer.java:97)
	at com.consol.citrus.channel.ChannelSyncConsumer.receive(ChannelSyncConsumer.java:60)
	at com.consol.citrus.messaging.AbstractSelectiveMessageConsumer.receive(AbstractSelectiveMessageConsumer.java:50)
	at com.consol.citrus.actions.ReceiveMessageAction.receive(ReceiveMessageAction.java:141)
	at com.consol.citrus.actions.ReceiveMessageAction.doExecute(ReceiveMessageAction.java:120)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.TestCase.executeAction(TestCase.java:220)
	at com.consol.citrus.dsl.runner.DefaultTestRunner.run(DefaultTestRunner.java:188)
	at com.consol.citrus.dsl.runner.DefaultTestRunner.receive(DefaultTestRunner.java:309)
	at service.test.stepdefinition.JdbcUpsertStepDef.mock_jdbc_server_environment_table(JdbcUpsertStepDef.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.cucumber.java.Invoker.invoke(Invoker.java:27)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:27)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:64)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:49)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:46)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:51)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:66)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:149)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:83)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:185)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:219)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
@christophd @svettwer

**Comment by christophd** [comment]
I assume the Http POST request should be done first in order to trigger the server logic. Simulating the stored procedure call via JDBC server should be the 2nd step. and finally you should verify the Http response in the last step.

If you do so please make sure to use the Http client fork mode when sending the Http POST request as the JDBC server simulation must be performed in parallel to the synchronous Http request.

Let me know if that works.
