### ISSUE TITLE
Access indexed bean properties via TestContext

### ISSUE THREAD

**Issue by tschlat** [citrusframework/citrus#820]
**Citrus Version**
3.1

**Expected behavior**
Indexed properties of variable should be accessible via TestContext.

Example:
Let **A** be a class with a property **int[] intVals**. 
Let a be an instance of **A** with  **intVals=new int[]{1,2,3,4}**. Let **a** be stored as variable **varA** in the TestContext.
Then 

`testContext.replaceDynamicContentInString("This is the second element of the array: ${varA.intVals[1]}")`

shoud yield

`"This is the second element of the array: 2"`

**Actual behavior**
When I try to access an indexed property of a variable via index, the following exception is thrown:

`com.consol.citrus.exceptions.CitrusRuntimeException: Failed to get variable - unknown field 'intVals[1]' on type ch.post.pf.sir.integration.SchemaValidationOnRequestTest$TestVar
	at com.consol.citrus.context.TestContext.getVariable(TestContext.java:251)
	at com.consol.citrus.context.TestContext.getVariableObject(TestContext.java:225)
	at com.consol.citrus.context.TestContext.getVariable(TestContext.java:204)
	at com.consol.citrus.context.TestContext.getVariable(TestContext.java:192)
	at com.consol.citrus.variable.VariableUtils.replaceVariablesInString(VariableUtils.java:177)
	at com.consol.citrus.context.TestContext.replaceDynamicContentInString(TestContext.java:431)
	at com.consol.citrus.context.TestContext.replaceDynamicContentInString(TestContext.java:416)'

**Test case sample**
[indexedPropertyAccessTest.zip](https://github.com/citrusframework/citrus/files/7685641/indexedPropertyAccessTest.zip)

**Comment by christophd** [comment]
+1
