### ISSUE TITLE
flaky JDK17 build pipeline

### ISSUE THREAD

**Issue by bbortt** [citrusframework/citrus#835]
the JDK 17 preview build seems pretty flaky.. A summary based on #812:

## [build 1](https://github.com/citrusframework/citrus/runs/4354247893?check_suite_focus=true)
PR had label `WIP`.

## [build 2](https://github.com/citrusframework/citrus/runs/4503590079?check_suite_focus=true)
```shell
Error:  Tests run: 31, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 34.072 s <<< FAILURE! - in TestSuite
Error:  SendReplyToIT(com.consol.citrus.jms.integration.SendReplyToIT)  Time elapsed: 5.207 s  <<< FAILURE!
com.consol.citrus.exceptions.TestCaseFailedException: 
Several actions failed in parallel container
	+ com.consol.citrus.exceptions.CitrusRuntimeException: org.springframework.jms.InvalidDestinationException: Cannot publish to a deleted Destination: temp-queue://ID:fv-az206-768-46147-1639385067292-4:113:1; nested exception is javax.jms.InvalidDestinationException: Cannot publish to a deleted Destination: temp-queue://ID:fv-az206-768-46147-1639385067292-4:113:1
	+ com.consol.citrus.exceptions.ReplyMessageTimeoutException: Action timeout after 5000 milliseconds. Failed to receive synchronous reply message on endpoint: 'temp-queue://ID:fv-az206-768-46147-1639385067292-4:113:1'
Caused by: com.consol.citrus.exceptions.ParallelContainerException: 
Several actions failed in parallel container
	+ com.consol.citrus.exceptions.CitrusRuntimeException: org.springframework.jms.InvalidDestinationException: Cannot publish to a deleted Destination: temp-queue://ID:fv-az206-768-46147-1639385067292-4:113:1; nested exception is javax.jms.InvalidDestinationException: Cannot publish to a deleted Destination: temp-queue://ID:fv-az206-768-46147-1639385067292-4:113:1
	+ com.consol.citrus.exceptions.ReplyMessageTimeoutException: Action timeout after 5000 milliseconds. Failed to receive synchronous reply message on endpoint: 'temp-queue://ID:fv-az206-768-46147-1639385067292-4:113:1'

2021-12-13 08:44:59,290 ActiveMQ ShutdownHook WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    SendReplyToIT>TestNGCitrusSpringSupport.run:110->TestNGCitrusSpringSupport.run:153 » TestCaseFailed
[INFO] 
Error:  Tests run: 31, Failures: 1, Errors: 0, Skipped: 0
...
[INFO] Citrus :: Endpoints :: JMS ......................... FAILURE [01:10 min]
```

## [build 3](https://github.com/citrusframework/citrus/actions/runs/1572123547)
```shell
Error:  Tests run: 18, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 264.498 s <<< FAILURE! - in TestSuite
Error:  testServiceInvocationWithArgument(com.consol.citrus.rmi.server.RmiServerTest)  Time elapsed: 131.288 s  <<< FAILURE!
java.lang.AssertionError: Faidled to invoke remote service
	at com.consol.citrus.rmi.server.RmiServerTest.testServiceInvocationWithArgument(RmiServerTest.java:101)
Caused by: java.rmi.ConnectException: 
Connection refused to host: 10.1.1.49; nested exception is: 
	java.net.ConnectException: Connection timed out
	at com.consol.citrus.rmi.server.RmiServerTest.testServiceInvocationWithArgument(RmiServerTest.java:99)
Caused by: java.net.ConnectException: Connection timed out
	at com.consol.citrus.rmi.server.RmiServerTest.testServiceInvocationWithArgument(RmiServerTest.java:99)

Error:  testServiceInvocationWithResult(com.consol.citrus.rmi.server.RmiServerTest)  Time elapsed: 131.06 s  <<< FAILURE!
java.lang.AssertionError: Faidled to invoke remote service
	at com.consol.citrus.rmi.server.RmiServerTest.testServiceInvocationWithResult(RmiServerTest.java:152)
Caused by: java.rmi.ConnectException: 
Connection refused to host: 10.1.1.49; nested exception is: 
	java.net.ConnectException: Connection timed out
	at com.consol.citrus.rmi.server.RmiServerTest.testServiceInvocationWithResult(RmiServerTest.java:150)
Caused by: java.net.ConnectException: Connection timed out
	at com.consol.citrus.rmi.server.RmiServerTest.testServiceInvocationWithResult(RmiServerTest.java:150)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    RmiServerTest>AbstractTestNGSpringContextTests.run:184->testServiceInvocationWithArgument:101 Faidled to invoke remote service
Error:    RmiServerTest>AbstractTestNGSpringContextTests.run:184->testServiceInvocationWithResult:152 Faidled to invoke remote service
[INFO] 
Error:  Tests run: 18, Failures: 2, Errors: 0, Skipped: 0
...
[INFO] Citrus :: Endpoints :: RMI ......................... FAILURE [04:25 min]
```

## [Build 4](https://github.com/citrusframework/citrus/actions/runs/1676635488)
```shell
Error:  Tests run: 32, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 83.528 s <<< FAILURE! - in TestSuite
Error:  httpServerZipFile(com.consol.citrus.http.integration.HttpServerZipFileJavaIT)  Time elapsed: 0.586 s  <<< FAILURE!
com.consol.citrus.exceptions.TestCaseFailedException: Received input stream is not equal to given control
	at com.consol.citrus.http.integration.HttpServerZipFileJavaIT.httpServerZipFile(HttpServerZipFileJavaIT.java:50)
Caused by: com.consol.citrus.exceptions.ValidationException: Received input stream is not equal to given control
	at com.consol.citrus.http.integration.HttpServerZipFileJavaIT.httpServerZipFile(HttpServerZipFileJavaIT.java:50)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    HttpServerZipFileJavaIT>TestNGCitrusSpringSupport.run:90->TestNGCitrusSpringSupport.run:166 » TestCaseFailed
[INFO] 
Error:  Tests run: 32, Failures: 1, Errors: 0, Skipped: 0
...
[INFO] Citrus :: Endpoints :: HTTP ........................ FAILURE [01:35 min]
```

## [Build 5](https://github.com/citrusframework/citrus/actions/runs/1691454795)

also notice how this run has no test summary despite the JDBC tests being run.

```shell
java.io.IOException: Failed to bind to /0.0.0.0:4567
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at spark.embeddedserver.jetty.EmbeddedJettyServer.ignite(EmbeddedJettyServer.java:149) ~[spark-core-2.7.1.jar:?]
	at spark.Service.lambda$init$2(Service.java:496) ~[spark-core-2.7.1.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[?:?]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89) ~[?:?]
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	... 9 more
2022-01-13 07:12:22.610|INFO |Thread-98|EmbeddedJettyServer - done
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
...
[INFO] Citrus :: Endpoints :: JDBC ........................ FAILURE [ 21.159 s]
```

**Comment by bbortt** [comment]
closing this for now, might be fixed for `v4.0.0` (see #922).
