### ISSUE TITLE
Cannot add a 2nd consumer to the same endpoint: DirectEndpoint only allows one consumer

### ISSUE THREAD

**Issue by sgleser** [citrusframework/citrus#915]
**Citrus Version**
3.3.0

**Expected behavior**
Citrus tests can call camel endpoints.

**Actual behavior**
Tests fail when trying to call Camel Endpoint with the following error:
**Cannot add a 2nd consumer to the same endpoint: .... DirectEndpoint only allows one consumer**
```
java


org.apache.camel.FailedToCreateConsumerException: Failed to create Consumer for endpoint: direct://create2. Reason: java.lang.IllegalArgumentException: Cannot add a 2nd consumer to the same endpoint: direct://create2. DirectEndpoint only allows one consumer.
	at org.apache.camel.support.cache.DefaultConsumerCache.acquirePollingConsumer(DefaultConsumerCache.java:107) ~[camel-support-3.18.3.jar:3.18.3]
	at org.apache.camel.support.cache.DefaultConsumerCache.receive(DefaultConsumerCache.java:138) ~[camel-support-3.18.3.jar:3.18.3]
	at org.apache.camel.impl.engine.DefaultConsumerTemplate.receive(DefaultConsumerTemplate.java:97) ~[camel-base-engine-3.18.3.jar:3.18.3]
	at com.consol.citrus.camel.endpoint.CamelSyncConsumer.receive(CamelSyncConsumer.java:81) ~[citrus-camel-3.3.0.jar:na]
	at com.consol.citrus.actions.ReceiveMessageAction.receive(ReceiveMessageAction.java:176) ~[citrus-base-3.3.0.jar:na]
	at com.consol.citrus.actions.ReceiveMessageAction.doExecute(ReceiveMessageAction.java:159) ~[citrus-base-3.3.0.jar:na]
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:59) ~[citrus-base-3.3.0.jar:na]
	at com.consol.citrus.DefaultTestCase.executeAction(DefaultTestCase.java:136) ~[citrus-base-3.3.0.jar:na]
	at com.consol.citrus.DefaultTestCaseRunner.run(DefaultTestCaseRunner.java:125) ~[citrus-base-3.3.0.jar:na]
	at com.consol.citrus.TestActionRunner.$(TestActionRunner.java:35) ~[citrus-api-3.3.0.jar:na]
	at org.example.routes.Camel3RouteTest.testCreate22(Camel3RouteTest.java:117) ~[test-classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725) ~[junit-platform-commons-1.8.2.jar:1.8.2]
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at com.consol.citrus.junit.jupiter.CitrusExtension.lambda$interceptTestMethod$1(CitrusExtension.java:139) ~[citrus-junit5-3.3.0.jar:na]
	at com.consol.citrus.common.DefaultTestLoader.lambda$doLoad$1(DefaultTestLoader.java:99) ~[citrus-base-3.3.0.jar:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at com.consol.citrus.common.DefaultTestLoader.doLoad(DefaultTestLoader.java:99) ~[citrus-base-3.3.0.jar:na]
	at com.consol.citrus.common.DefaultTestLoader.load(DefaultTestLoader.java:77) ~[citrus-base-3.3.0.jar:na]
	at com.consol.citrus.junit.jupiter.CitrusExtension.interceptTestMethod(CitrusExtension.java:147) ~[citrus-junit5-3.3.0.jar:na]
	at com.consol.citrus.junit.jupiter.spring.CitrusSpringExtension.interceptTestMethod(CitrusSpringExtension.java:92) ~[citrus-junit5-3.3.0.jar:na]
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57) ~[junit5-rt.jar:na]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) ~[junit-rt.jar:na]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) ~[idea_rt.jar:na]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) ~[junit-rt.jar:na]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235) ~[junit-rt.jar:na]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54) ~[junit-rt.jar:na]
Caused by: java.lang.IllegalArgumentException: Cannot add a 2nd consumer to the same endpoint: direct://create2. DirectEndpoint only allows one consumer.
	at org.apache.camel.component.direct.DirectComponent.addConsumer(DirectComponent.java:98) ~[camel-direct-3.18.3.jar:3.18.3]
	at org.apache.camel.component.direct.DirectConsumer.doStart(DirectConsumer.java:47) ~[camel-direct-3.18.3.jar:3.18.3]
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119) ~[camel-api-3.18.3.jar:3.18.3]
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113) ~[camel-api-3.18.3.jar:3.18.3]
	at org.apache.camel.support.EventDrivenPollingConsumer.doStart(EventDrivenPollingConsumer.java:288) ~[camel-support-3.18.3.jar:3.18.3]
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119) ~[camel-api-3.18.3.jar:3.18.3]
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113) ~[camel-api-3.18.3.jar:3.18.3]
	at org.apache.camel.impl.engine.AbstractCamelContext.internalAddService(AbstractCamelContext.java:1577) ~[camel-base-engine-3.18.3.jar:3.18.3]
	at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1498) ~[camel-base-engine-3.18.3.jar:3.18.3]
	at org.apache.camel.support.cache.ServicePool$SinglePool.acquire(ServicePool.java:238) ~[camel-support-3.18.3.jar:3.18.3]
	at org.apache.camel.support.cache.ServicePool$SinglePool.acquire(ServicePool.java:216) ~[camel-support-3.18.3.jar:3.18.3]
	at org.apache.camel.support.cache.ServicePool.acquire(ServicePool.java:112) ~[camel-support-3.18.3.jar:3.18.3]
	at org.apache.camel.support.cache.PollingConsumerServicePool.acquire(PollingConsumerServicePool.java:28) ~[camel-support-3.18.3.jar:3.18.3]
	at org.apache.camel.support.cache.DefaultConsumerCache.acquirePollingConsumer(DefaultConsumerCache.java:101) ~[camel-support-3.18.3.jar:3.18.3]
	... 89 common frames omitted

```

**Test case sample**

Run tests inside the Camel on Springboot project on this repository:
https://github.com/sgleser/camel3-citrustests  

Branch: [main](https://github.com/sgleser/camel3-citrustests) - On this branch **CamelSyncEndpoint** is used for the direct calls.

Branch: [camel-sync-error](https://github.com/sgleser/camel3-citrustests/tree/camel-sync-error) - For the direct calls we used **camel:sync:...**

The problem is reproduced on both branches, however with CamelSyncEndpoint almost always.
It can different on different machines because it is probably a race condition problem.

**Comment by christophd** [comment]
Camel endpoints in Citrus are bidirectional. Citrus is able to act as a producer and as a consumer on the same endpoint. It depends on what operation you call first `send()` or `receive()` that decides what part Citrus is going to be, producer or consumer.

That being said I think it is the `fork()` on the `send()` that makes the problems. removing it stabilizes the tests for me.

Adding the `fork` may lead to the situation where the `receive()` in the next step is actually performed before the `send()`. this leads to the situation that there is a consumer from Citrus on the CamelSync endpoint and with the CamelContext we have another consumer on the same route producing the error.

I suggest to remove the `fork` or if there still are some racing conditions explicitly force the Camel endpoint in Citrus to act as a producer. You can do this in the config right after the endpoint is created. Also I prefer to use the endpoint DSL in Citrus as it is way more straight forward in the configuration. Something like this:

```java
    @Bean(name = "create1Endpoint")
    public CamelSyncEndpoint create1Endpoint() {
        CamelSyncEndpoint create1Endpoint = camel()
                .synchronous()
                .camelContext(context)
                .endpointUri("direct:create1")
                .pollingInterval(300)
                .timeout(1000L)
                .build();

        create1Endpoint.createProducer();

        return create1Endpoint;
    }

    @Bean(name = "create2Endpoint")
    public CamelSyncEndpoint create2Endpoint() {
        CamelSyncEndpoint create2Endpoint = camel()
                .synchronous()
                .camelContext(context)
                .endpointUri("direct:create2")
                .pollingInterval(300)
                .timeout(1000L)
                .build();

        create2Endpoint.createProducer();

        return create2Endpoint;
    }
```

Immediately calling createProducer() on that endpoint to make sure that the Citrus endpoint acts as a producer and never as a consumer.
