### ISSUE TITLE
Remote plugin: Test case fails, but citrus succeeds

### ISSUE THREAD

**Issue by turing85** [citrusframework/citrus#949]
**Citrus Version**: 3.4.0 (earlier version probably as well)

**Expected behavior**
Test case fails and citrus report an error, or test case succeeds and citrus succeeds.

**Actual behavior**
Test case fails, but citrus succeeds.

**Test case sample**
- Checkout https://github.com/turing85/citrus-playground/tree/bug/test-fails-wrongly-citrus-succeeds:
  ```bash
  git clone https://github.com/turing85/citrus-playground.git
  cd citrus-playground
  git fetch
  git switch bug/test-fails-wrongly-citrus-succeeds
  ```
- Build sut and citrus:
  ```bash
  ./mvnw clean package
  ```
- Deploy sut and citrus through `docker-compose`,
  ```bash
  docker-compose -f local-deployment/docker-compose.yml up --build --detach
  ```
- Attach to `service`-logs:
  ```bash
  docker logs -f service
  ```
- In a separate console, attach to the `citrus`-logs:
  ```bash
  docker logs -f citrus-tests
  ```
- In another shell, trigger remote execution:
  ```bash
  cd citrus-playground
  ./mvnw --projects citrus --activate-profiles trigger-citrus-remote verify
  ```
- Observe that the execution of the `citrus-remote-maven-plugin` succeeds:
  ```
  [INFO] Scanning for projects...
  [INFO] 
  [INFO] ----------------< de.turing85:citrus-playground-citrus >----------------
  [INFO] Building Citrus Playground :: Citrus 1.0-SNAPSHOT
  [INFO] --------------------------------[ jar ]---------------------------------
  [INFO] 
  [INFO] --- citrus-remote-maven-plugin:3.4.0:test (trigger-citrus-remote) @ citrus-playground-citrus ---
  [INFO] Waiting for remote tests to finish ...
  [INFO] 
  [INFO] 
  INFO	| ------------------------------------------------------------------------
  INFO	| 
  INFO	| CITRUS TEST RESULTS
  INFO	| 
  INFO	|  GetMetricsIT.getMetrics ........................................ SUCCESS
  INFO	|  GetHealthIT.getHealth .......................................... SUCCESS
  INFO	|  GetHelloIT.getHello ............................................ SUCCESS
  INFO	| 
  INFO	| TOTAL:	3
  INFO	| FAILED:	0 (0.0%)
  INFO	| SUCCESS:	3 (100.0%)
  INFO	| 
  INFO	| ------------------------------------------------------------------------
  ...
  ```
- Observe that the test execution within the `citrus-tests`-container throws a `MessageTimeoutException`, but the test still succeeds:
  ```
   ...
  2023-05-29 00:56:59.089  INFO --- [pool-2-thread-1] c.c.c.h.c.HttpClient                     : Sending HTTP message to: 'http://service:8080/hello'
  2023-05-29 00:56:59.578  INFO --- [qtp634221858-26] c.c.c.r.CitrusRemoteApplication          : GET http://localhost:4567/results?timeout=15000
  2023-05-29 00:57:00.090  WARN --- [cTaskExecutor-1] c.c.c.a.AbstractAsyncTestAction          : Async test action execution raised error
  com.consol.citrus.exceptions.MessageTimeoutException: Action timeout after 1000 milliseconds. Failed to receive message on endpoint: 'httpServer.inbound'
  	at com.consol.citrus.endpoint.direct.DirectConsumer.receive(DirectConsumer.java:69)
  	at com.consol.citrus.endpoint.direct.DirectSyncConsumer.receive(DirectSyncConsumer.java:41)
  	at com.consol.citrus.messaging.AbstractSelectiveMessageConsumer.receive(AbstractSelectiveMessageConsumer.java:50)
  	at com.consol.citrus.actions.ReceiveMessageAction.receive(ReceiveMessageAction.java:178)
  	at com.consol.citrus.actions.ReceiveMessageAction.doExecute(ReceiveMessageAction.java:160)
  	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:59)
  	at com.consol.citrus.container.AbstractActionContainer.executeAction(AbstractActionContainer.java:71)
  	at com.consol.citrus.container.Async$1.doExecuteAsync(Async.java:60)
  	at com.consol.citrus.actions.AbstractAsyncTestAction.lambda$doExecute$0(AbstractAsyncTestAction.java:51)
  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  	at java.base/java.lang.Thread.run(Unknown Source)
  2023-05-29 00:57:00.091  INFO --- [cTaskExecutor-1] c.c.c.c.Async                            : Apply error actions after async container ...
  2023-05-29 00:57:00.313  INFO --- [ qtp38350903-43] c.c.c.e.d.DirectSyncProducer             : Message was sent to queue: 'httpServer.inbound'
  2023-05-29 00:57:01.314  WARN --- [ qtp38350903-43] c.c.c.e.d.DirectEndpointAdapter          : Action timeout after 1000 milliseconds. Failed to receive synchronous reply message on endpoint: 'httpServer.inbound'
  2023-05-29 00:57:01.833  INFO --- [pool-2-thread-1] c.c.c.h.c.HttpClient                     : HTTP message was sent to endpoint: 'http://service:8080/hello'
  ...
  2023-05-29 00:57:03.346  INFO --- [pool-2-thread-1] c.c.c.r.LoggingReporter                  : CITRUS TEST RESULTS
  2023-05-29 00:57:03.346  INFO --- [pool-2-thread-1] c.c.c.r.LoggingReporter                  : 
  2023-05-29 00:57:03.347  INFO --- [pool-2-thread-1] c.c.c.r.LoggingReporter                  :  GetHealthIT.getHealth .......................................... SUCCESS
  2023-05-29 00:57:03.347  INFO --- [pool-2-thread-1] c.c.c.r.LoggingReporter                  :  GetHelloIT.getHello ............................................ SUCCESS
  2023-05-29 00:57:03.348  INFO --- [pool-2-thread-1] c.c.c.r.LoggingReporter                  :  GetMetricsIT.getMetrics ........................................ SUCCESS
  2023-05-29 00:57:03.348  INFO --- [pool-2-thread-1] c.c.c.r.LoggingReporter                  : 
  2023-05-29 00:57:03.348  INFO --- [pool-2-thread-1] c.c.c.r.LoggingReporter                  : TOTAL:	3
  2023-05-29 00:57:03.351  INFO --- [pool-2-thread-1] c.c.c.r.LoggingReporter                  : FAILED:	0 (0.0%)
  2023-05-29 00:57:03.351  INFO --- [pool-2-thread-1] c.c.c.r.LoggingReporter                  : SUCCESS:	3 (100.0%)
  ...
  ===============================================
  Default Suite
  Total tests run: 3, Passes: 2, Failures: 1, Skips: 0
  ===============================================
  ...
  ```
- Observe in the `service`-logs that the service sends an empty string as repsonse:
  ```
  2023-05-29 00:57:01,339 INFO  [de.tur.cit.tes.ser.HelloEndpoint] (executor-thread-1) sending "" as response
  ```
  which should not pass the verification [here (`github.com`)](https://github.com/turing85/citrus-playground/blob/main/citrus/src/test/java/de/turing85/citrus/tests/citrus/GetHelloIT.java#L44)

**Additional Information**
- The error disappears when we increase the timeout on the http server, see [here](https://github.com/turing85/citrus-playground/blob/main/citrus/src/test/java/de/turing85/citrus/tests/citrus/configuration/Http.java#L34)
- [Here](https://github.com/citrusframework/citrus/files/11587175/citrus.log) is the full log of the run
- If we execute the tests a second time by calling `./mvnw verify`, the test will fail again, but with an `ValidationException`. [Here](https://github.com/citrusframework/citrus/files/11587177/citrus2.log) is the log of the 2nd run that failed.

**Comment by turing85** [comment]
Sorry, had to update the code. Don't know how I was able to miss that. Reproducer is now up-to-date and actually reproduces the problem.
